#!/usr/bin/env bash

for x in 0 1 2 3 4 5 6 7 8 9 ; do
  for y in 0 1 2 3 4 5 6 7 8 9 ; do
    curl -sSLO -w "
               time_namelookup:  %{time_namelookup} s
                  time_connect:  %{time_connect} s
               time_appconnect:  %{time_appconnect} s
              time_pretransfer:  %{time_pretransfer} s
                 time_redirect:  %{time_redirect} s
            time_starttransfer:  %{time_starttransfer} s
                speed_download:  %{speed_download} bytes/s
                 url_effective:  %{url_effective}
                               ----------
                    time_total:  %{time_total} s
" "${1}"
  done
done
